#!/usr/bin/env sh
# This file is part of java-llvm. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/java-llvm/master/COPYRIGHT. No part of java-llvm, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2016 The developers of java-llvm. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/java-llvm/master/COPYRIGHT.

toolsPath='/usr/local/opt/llvm37/lib/llvm-3.7/bin'
systemHeadersPath='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include'

_llvm_tool()
{
	(
		export PATH="$toolsPath":"$PATH"
		"$@"
	)
}

_llvm_architecture_help()
{
	local architecture="$1"
	local helpOn="cpu"
	
	_llvm_tool llvm-as </dev/null | _llvm_tool llc -march="$architecture" -m${helpOn}=help
}

_llvm_architecture_help_cpus()
{
	_llvm_architecture_help "$1" 'cpu'
}

_llvm_architecture_help_attributes()
{
	_llvm_architecture_help "$1" 'attr'
}

compileToAssemblyLanguage()
{
	local outputFilePath="$baseFilePath".ll
	
	if [ -f "$outputFilePath" ]; then
		if $force; then
			rm -rf "$outputFilePath"
		else
			return 0
		fi
	fi
	
	_llvm_tool clang -c -S -emit-llvm -isystem "$systemHeadersPath" "$filePath"
}

assembleToBitCode()
{
	local outputFilePath="$baseFilePath".bc
	
	_llvm_tool llvm-as -o="$outputFilePath" "$baseFilePath".ll
}

assembleToLocalAssemblyAtt()
{
	local outputFilePath="$baseFilePath".att.s
	
	_llvm_tool llc -o="$outputFilePath" --x86-asm-syntax=att "$baseFilePath".ll
}

assembleToLocalAssemblyIntel()
{
	local outputFilePath="$baseFilePath".intel.s
	
	_llvm_tool llc -o="$outputFilePath" --x86-asm-syntax=intel "$baseFilePath".ll
}

optimiseAssemblyLanguage()
{
	local outputFilePath="$baseFilePath".opt.ll
	
	_llvm_tool opt -o="$outputFilePath" -S "$baseFilePath".ll
}

loop()
{
	local extension="$1"
	shift 1
	
	local filePath
	for filePath in *."$extension"; do
		if [ ! -f "$filePath" ]; then
			continue
		fi
		
		local withoutPeriods="${filePath%%.*}"
		if [ "$withoutPeriods"."$extension" != "$filePath" ]; then
			continue
		fi
		
		local baseFilePath="${filePath%.*}"
		
		local action
		for action in "$@"
		do
			$action  "$filePath" "$baseFilePath"
		done
	done
}

architecture()
{
	local architecture
	for architecture in 'x86' 'x86-64'
	do
		_llvm_architecture_help_cpus "$architecture"
		_llvm_architecture_help_attributes "$architecture"
	done
}

main()
{
	local operation
	if [ $# -eq 0 ]; then
		operation=compile
	else
		operation="$1"
	fi
	
	case "$operation" in
		
		compile)
			local force=false
			
			if [ "$2" = "--force" ]; then
				force=true
			fi
			
			if [ "$2" = "-f" ]; then
				force=true
			fi
			
			loop c compileToAssemblyLanguage assembleToBitCode assembleToLocalAssemblyAtt assembleToLocalAssemblyIntel optimiseAssemblyLanguage
		;;
		
		architecture)
			architecture
		;;
		
	esac
}

main "$@"
