; Generated by stormmq llvm
; Generated from com.stormmq.llvm.example.LlvmExample.java

define external default ccc i32 @com.stormmq.llvm.example.LlvmExample.add1(i32 %x, i32 %y) {
    %tmp1 = add i32 %x, %y
    ret i32 %tmp1
}

// Making a function private gives it 'hidden' visibility
define external hidden ccc i32 @com.stormmq.llvm.example.LlvmExample.add2(i32 %x, i32 %y) {
    %tmp1 = add i32 %x, %y
    ret i32 %tmp1
}
